server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite ?? ??
    session:
      tracking-modes: cookie
      timeout: 30m
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL # H2 ??????? ??? ??? ????, MySQL ?? ??? ???
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # H2 ??? ????? ????? ?? ??????? ??? ? ??? ?
  jpa:
    hibernate:
      ddl-auto: create # ??????? ??? ? ?????? ???? ???? ??
    properties:
      '[hibernate.default_batch_fetch_size]': 100 # ?? ?? ???? ?? ?? ?? ??
      '[hibernate.format_sql]': true # SQL ??? ???? ??? ??
    show-sql: true # JPA? ?? ???? SQL ??? ???? ??? ??? ??
    defer-datasource-initialization: true # ?? ???
    open-in-view: false
  sql:
    init:
      data-locations:
        - classpath:db/data.sql # ?? ???? ?? SQL ???? ?? ?? ??

logging:
  level:
    '[com.example.bank]': DEBUG # ??????? ???? ?? ?? ??? DEBUG? ??
    '[org.hibernate.orm.jdbc.bind]': TRACE # Hibernate? SQL ??? ??? TRACE ??? ???? ??? ?? ??